FROM python:3.9-slim
WORKDIR /projects
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8501
CMD ["streamlit", "run", "streamlit_app1_up1.py", "--server.port=8501", "--server.address=0.0.0.0"]